loading: Loading...
search: Search
read_more: Read more
encrypted_placeholder: This article is encrypted. Enter the password.
toc: Table of contents
back_to_top: Back to top
view_comments: View comments
go_to_bottom: Go to bottom
comments: Comments
bottom: Bottom
close_toc: Close table of contents
open_toc: Open table of contents
icp: "ICP filing:"
code_expand: "Expand all (%s lines)"
code_collapse: Collapse
copy_code: Copy code
copied_code: Copied
